# Question

Look at this function:

```js
const bailOut = () => {
  for (let i = 0; i < 5; i++) {
    if (i > 3) return;
    console.log("Inside the loop", i);
  }
  console.log("Outside the loop");
};
```

Is that `console.log('Outside the loop');` ever going to run? Why or why not?

# Answer

It will not. That is because inside the loop there is a return statement. The loop will iterate until the if condition inside is met, then will leave the function entirely when the return statement runs.

# Teacher Feedback
